import os
import json

def run(service, app_name, *args, **kwargs):
    """
    Logic untuk membangun folder dan manifest aplikasi baru secara otomatis.
    Memastikan struktur mematuhi standar FloworkOS.
    """
    base_path = service.base_app_path
    app_dir = os.path.join(base_path, app_name)

    # 1. Buat direktori utama aplikasi
    if not os.path.exists(app_dir):
        os.makedirs(app_dir)
        os.makedirs(os.path.join(app_dir, "logic")) # Folder untuk Atomic Cells
    else:
        return {"status": "error", "message": f"App '{app_name}' already exists."}

    # 2. Buat manifest.json standar
    manifest = {
        "id": app_name,
        "name": app_name.replace("_", " ").title(),
        "version": "1.0.0",
        "entry_point": "main.py",
        "description": "Auto-generated by Flowork App-Builder",
        "author": "FloworkOS"
    }

    with open(os.path.join(app_dir, "manifest.json"), 'w') as f:
        json.dump(manifest, f, indent=4)

    # 3. Buat file main.py standar (Atomic Template)
    main_content = """def run(app_context, *args, **kwargs):
    return {"status": "success", "message": "App initiated successfully"}
"""
    with open(os.path.join(app_dir, "main.py"), 'w') as f:
        f.write(main_content)

    # 4. Trigger Sync agar Hub mengenali app baru tanpa restart
    service.sync()

    return {
        "status": "success",
        "message": f"App '{app_name}' scaffolded successfully at {app_dir}"
    }